# Generated by Django 4.2.23 on 2025-10-17 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Госномер"
                    ),
                ),
                ("make", models.CharField(max_length=64, verbose_name="Марка")),
                ("model", models.CharField(max_length=64, verbose_name="Модель")),
                (
                    "last_service_mileage",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Пробег последнего ТО",
                    ),
                ),
                (
                    "service_interval_km",
                    models.PositiveIntegerField(
                        default=10000,
                        validators=[django.core.validators.MinValueValidator(1000)],
                        verbose_name="Интервал ТО км",
                    ),
                ),
                (
                    "next_service_mileage",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Пробег следующего ТО"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=64, verbose_name="Фамилия")),
                (
                    "phone",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver",
                        to="core.automobile",
                        verbose_name="Привязанный автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "status",
                    models.CharField(
                        choices=[("free", "Свободен"), ("busy", "Занят")],
                        default="free",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот для записи",
                "verbose_name_plural": "Слоты для записи",
                "ordering": ["date", "time"],
                "unique_together": {("date", "time")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("cancelled_manager", "Отменена менеджером"),
                            ("cancelled_user", "Отменена пользователем"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.automobile",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.driver",
                        verbose_name="Водитель",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.slot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["slot__date", "slot__time"],
            },
        ),
    ]
